

SELECT * FROM ESTUDANTES;

SELECT * FROM CURSOS;

SELECT * FROM INSCRICOES;

SELECT nome FROM ESTUDANTES WHERE id_estudante = 1;

SELECT nome_curso FROM CURSOS WHERE nome_curso like 'F%';

SELECT COUNT(*) FROM INSCRICOES WHERE id_curso = 101;


